# managed-by=mohavise-mikrotik-dns-policy-routing
# project=mikrotik-dns-policy-routing
# service=debian
# do-not-edit-generated-files

SERVICE_ID="debian"
SERVICE_NAME="Debian"
LIST_NAME="DST-DEBIAN-TO-OUTBOUND"
LIST_NAME_PATTERN="DST-<GROUP>-TO-<TARGET>"

DOMAIN_SOURCE_NAME="Debian mirror documentation"
DOMAIN_SOURCE_TYPE="official-repository-domains"

DOMAIN_COMMENT_PREFIX="debian:"
CIDR_COMMENT="debian-cidr"

MIN_DOMAIN_RULES=4
MIN_CIDR_RULES=0