# managed-by=mohavise-mikrotik-dns-policy-routing
# project=mikrotik-dns-policy-routing
# service=speedtest
# do-not-edit-generated-files

SERVICE_ID="speedtest"
SERVICE_NAME="Speedtest"
LIST_NAME="SPEEDTEST"
LIST_NAME_PATTERN="CUSTOM-EXACT-LIST"

DOMAIN_SOURCE_NAME="Local MikroTik DNS policy list"
DOMAIN_SOURCE_TYPE="manual-curated"

DOMAIN_COMMENT_PREFIX="speedtest:"
CIDR_COMMENT="speedtest-cidr"

MIN_DOMAIN_RULES=20
MIN_CIDR_RULES=0
