#!/bin/sh
set -eu

LIST_NAME="${LIST_NAME:-DST-TO-OUTBOUND}"
PROJECT="MikroTik DNS Policy Routing"
MAINTAINER="mohavise"
LAST_UPDATE="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

mkdir -p generated

header() {
  cat <<EOF
# Project: $PROJECT
# Maintainer: $MAINTAINER
# Generated by: scripts/build.sh
# Address-list: $LIST_NAME
# Last update: $LAST_UPDATE
# WARNING: Do not edit this file manually. Edit sources/ instead.

EOF
}

normalize_domains() {
  find sources/domains -type f -name '*.txt' | sort | while read -r file; do
    sed 's/#.*$//' "$file" | tr -d ' \t\r' | sed '/^$/d' | tr '[:upper:]' '[:lower:]'
  done | sort -u
}

normalize_cidr() {
  find sources/cidr -type f -name '*.txt' | sort | while read -r file; do
    sed 's/#.*$//' "$file" | tr -d ' \t\r' | sed '/^$/d'
  done | sort -u
}

regex_for_domain() {
  domain="$1"
  escaped=$(printf '%s' "$domain" | sed 's/\./\\\\./g')
  printf '(^|.*\\\\.)%s\\$' "$escaped"
}

build_domains() {
  header
  echo "/ip dns static"
  echo
  normalize_domains | while read -r domain; do
    regex=$(regex_for_domain "$domain")
    comment=$(printf '%s' "$domain" | sed 's/"//g')
    printf ':do { add regexp="%s" type=FWD address-list=%s comment="%s" } on-error={}\n' "$regex" "$LIST_NAME" "$comment"
  done
}

build_cidr() {
  header
  echo "/ip firewall address-list"
  echo
  normalize_cidr | while read -r cidr; do
    printf ':do { add list=%s address=%s comment="cidr-source" } on-error={}\n' "$LIST_NAME" "$cidr"
  done
}

build_domains > generated/dst-to-outbound-domains.rsc
build_cidr > generated/dst-to-outbound-cidr.rsc
{
  cat generated/dst-to-outbound-domains.rsc
  echo
  cat generated/dst-to-outbound-cidr.rsc
} > generated/dst-to-outbound-all.rsc

printf 'Generated files:\n'
printf '  generated/dst-to-outbound-domains.rsc\n'
printf '  generated/dst-to-outbound-cidr.rsc\n'
printf '  generated/dst-to-outbound-all.rsc\n'
